// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnVBBxZNv7NKW8UZ6hss8iD7bIlYVoaw',
    appId: '1:321003637945:web:94a3b85adad4089bfb9f68',
    messagingSenderId: '321003637945',
    projectId: 'my-cookbook-41741',
    authDomain: 'my-cookbook-41741.firebaseapp.com',
    storageBucket: 'my-cookbook-41741.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAau2SAnSKHF1FQB988_giZMvPO_pNfCiw',
    appId: '1:321003637945:android:f9c0d00156b8711cfb9f68',
    messagingSenderId: '321003637945',
    projectId: 'my-cookbook-41741',
    storageBucket: 'my-cookbook-41741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySIe5pxmLIIguWJ6bYF7AFWRnr9n8gR0',
    appId: '1:321003637945:ios:54d854f95198db89fb9f68',
    messagingSenderId: '321003637945',
    projectId: 'my-cookbook-41741',
    storageBucket: 'my-cookbook-41741.appspot.com',
    iosClientId: '321003637945-rq2vu4adpco6bd1u6cubjo594n8a53mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCySIe5pxmLIIguWJ6bYF7AFWRnr9n8gR0',
    appId: '1:321003637945:ios:54d854f95198db89fb9f68',
    messagingSenderId: '321003637945',
    projectId: 'my-cookbook-41741',
    storageBucket: 'my-cookbook-41741.appspot.com',
    iosClientId: '321003637945-rq2vu4adpco6bd1u6cubjo594n8a53mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookbook',
  );
}
