// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBerNAt6aWAacnnZbVXsyFX8IWFcqcPDZA',
    appId: '1:871500880528:web:7aa9692dac54b0b4ba1615',
    messagingSenderId: '871500880528',
    projectId: 'hack-334ed',
    authDomain: 'hack-334ed.firebaseapp.com',
    storageBucket: 'hack-334ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIz7n4EEkfFgluxhPkLYCM8MdVsawnjE8',
    appId: '1:871500880528:android:6cb24b75db620f85ba1615',
    messagingSenderId: '871500880528',
    projectId: 'hack-334ed',
    storageBucket: 'hack-334ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgBBKxOmpLGT0aFTNg4gRA9lHDfB-u9Uw',
    appId: '1:871500880528:ios:bb9aa39e0ba7c41bba1615',
    messagingSenderId: '871500880528',
    projectId: 'hack-334ed',
    storageBucket: 'hack-334ed.appspot.com',
    iosClientId: '871500880528-7vlfkn042bra6o2rost81bo7h5ns8a8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgBBKxOmpLGT0aFTNg4gRA9lHDfB-u9Uw',
    appId: '1:871500880528:ios:bb9aa39e0ba7c41bba1615',
    messagingSenderId: '871500880528',
    projectId: 'hack-334ed',
    storageBucket: 'hack-334ed.appspot.com',
    iosClientId: '871500880528-7vlfkn042bra6o2rost81bo7h5ns8a8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookbook',
  );
}
